name: Python App CI/CD Pipeline with Direct Deployment




on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  

jobs:

  run-tests:
    name: Run Pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest python-dotenv azure-identity azure-keyvault-secrets

      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run pytest
        env:
          KEY_VAULT_NAME: ${{ secrets.KEY_VAULT_NAME }}
          G_TOKEN: ${{ secrets.G_TOKEN }} 
        run: |
          pytest tests/


  build-and-deploy:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
    # Azure Login using GitHub Secrets
    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Execute the Update Script on the VMSS
    - name: Deploy to Azure VMSS
      run: |
        az vmss extension set \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --vmss-name ${{ secrets.VMSS_NAME }} \
          --name CustomScript \
          --force-update \
          --publisher Microsoft.Azure.Extensions \
          --settings '{"commandToExecute": "/home/azureuser/stage6.5/update.sh"}'
